[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[cursor]
blink_interval = 500
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 9.5

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[shell]
program = "nu"

[shell.url.launcher]
program = "xdg-open"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 7
y = 7
